### ISSUE TITLE
[Concept]Sub Chain

### ISSUE THREAD

**Issue by oliverde8** [oliverde8/php-etl#14]
With the split operation makig a real debut #10 we need a way to have shared operations between execution branches. 

This is also necessery when developping chains with multiple common steps. 

2 ways to define these: 
1. Add new subOperations section to existing yamls where these can be listed. 
2. Allow a dedicated yaml file to be loaded

Example of definition 
```yaml
subChains:
  mySubChain:1
    op1: {operation: toto}
  mySubChain:2
    op1: {operation: roro}
```

Example of usage
```yaml
myOperation:
  operation: subChain
```

or if the subChain is defined in a different yaml: 
```yaml
myOperation:
  operation: myFile.yaml:subChain
```

We should be able to share subChains instances, so for example if the subChain writes a file then if configured in `share: true` and is used multiple times in the same chain all the data will be written in the same file. How to handle StopItem requires thinking.
