### ISSUE TITLE
Allo usage of input options to be used in the operation options

### ISSUE THREAD

**Issue by oliverde8** [oliverde8/php-etl#20]
Example

```yaml
filter-subscribed:
  operation: write-csv
  options:
     filename: "{file2.path}" #uses symfony expression language
```
